[package]
name = "cart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
buddy-alloc = "0.4.1"
glam = "0.24.2"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
